/*
 * colfinder.c
 *
 * Copyright(C) 2026 Matteo Zapparoli - zapparoli.matteo@gmail.com
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Compile: gcc -O3 colfinder.c prng.c -o colfinder
 *
 * Sintax:
 *  colfinder [start]
 *
 * No args prints help
 *
 * Collision analysis tool for 64-bit pseudo-random number generators 
 * Parses the first 16 billion numbers generated by a PRNG defined in
 * the file prng.c; prints any collisions (duplicate numbers) found.
 * It requires about 4 GB RAM.
 * It takes about 30 to 50 minutes.
 * For further details, please refer to https://github.com/matteo65/colfinder
 *
 */

#include <stdio.h>
#include <stdint.h> // uint64_t
#include <stdlib.h> // exit()
#include <stdarg.h> // vsprintf()
#include <errno.h> // errno
#include <string.h> // strcmp()
#include <inttypes.h> // PRIu64
#include <time.h> // time()

#include "prng.h"

#define VERSION "1.0"

// Global variables
static uint64_t *array = NULL; // Allocated with calloc()
static size_t narray; // length of array

static uint64_t collision[15];
static size_t ncollision;

// Protypes
static void fatal_error(const char *frm,...);
static void failure(const char *frm,...);
static void array_free(void);
static void array_sort(void);
static void smart_sort(int low, int high);
static void copyright(void);
static void usage(void);
static char *time_interval(time_t t);

int main(int argc, char *argv[])
{
	if(argc <= 1) {
		usage();
		return EXIT_SUCCESS;
	}
	
	if(argc != 2) {
		fatal_error("invalid arguments number");
	}
	
	if(strcmp(argv[1], "start")) {
		fatal_error("unknow %s argument", argv[1]);
	}

	time_t now = time(NULL); // To calcolate elapsed and remaning time
	
	array = (uint64_t*)calloc(505000000, sizeof(uint64_t));
	
	if(array == NULL) {
		fatal_error("no memory available");
	}
	
	copyright();
	
	printf("Testing %s\n", prng_name);
	printf("Sample size: 16 billions\n");

	ncollision = 0;
	
	for(size_t i = 0; i < 32; i++) {
		printf("\nBlock %zu/32\n", i + 1);
		
		set_seed();
		
		narray = 0;
		
		for(size_t j = 0; j < 16000000000; j++) {
			uint64_t value = next();
			if((value & 0x1F) == i) {
				array[narray++] = value;
				if(narray == 505000000) {
					failure("The PRNG does not have a uniform distribution!");
 				}
			}
		}
		
		if(narray <= 495000000) {
			failure("The PRNG does not have a uniform distribution !");
		}
		
		printf("Length: %zu\n", narray);
		
		array_sort();
		
		for(size_t j = 1; j < narray; j++) {
			if(array[j - 1] == array[j]) {
				printf("--------> Collision: %" PRIu64 "\n", array[j]);
				
				if(ncollision == 15) {
					failure("Number of collisions exceeds the maximum expected value!");
				}
				
				for(size_t k = 0; k < ncollision; k++) {
					if(collision[k] == array[j]) {
						failure("Collision %" PRIu64 " already present!", array[j]);
					}
				}
				collision[ncollision++] = array[j];
			}
		}
		
		time_t elapsed = time(NULL) - now;
		
		printf("Elapsed time: %s\n", time_interval(elapsed));
		
		if(i > 0) {
			printf("Remaining time: %s\n", time_interval((elapsed / (i + 1)) * (31 - i)));
		}
	}
	
	if(ncollision == 0) {
		failure("No collisions found!");
	}
	
	if(ncollision < 2 || ncollision >= 14) {
		printf("\nSUSPICIOUS: Found %zu collisions found, far from the expected value 6.94; it is recommended to repeat the test with other seeds\n", ncollision);
	}
	else {
		printf("\nSUCCESS: Found %zu collisions compatible with the expected number of collisions 6.94\n", ncollision);
	}
	
	array_free();
	
	return EXIT_SUCCESS;
}

static void fatal_error(const char *frm,...)
{
	char message[1000];
	va_list argptr;

	va_start(argptr, frm);
	(void) vsprintf(message, frm, argptr);
	va_end(argptr);

	if(errno) {
		fprintf(stderr, "*** Error: %s: %s\n", message, strerror(errno));
	} 
	else {
		fprintf(stderr, "*** Error: %s\n", message);
	}
	exit(EXIT_FAILURE);
}

static void failure(const char *frm,...)
{
	char message[1000];
	va_list argptr;

	va_start(argptr, frm);
	(void) vsprintf(message, frm, argptr);
	va_end(argptr);
	
	printf("\nFAIL: %s\n", message);
	
	array_free();
	
	exit(EXIT_FAILURE);
}

static void array_free(void)
{
	if(array != NULL) 
		free(array);
	array = NULL;
}

// Return a static string formating the time interval into hh:mm:ss string
static char *time_interval(time_t t)
{
	static char str[25];
	
	unsigned hh = t / 3600;
	unsigned mm = (t - 3600 * hh) / 60;
	unsigned ss = t - 3600 * hh - 60 * mm;
	
	sprintf(str, "%02u:%02u:%02u", hh, mm, ss);
	
	return str;
}

// Sort array[] in ascending order. Based on quicksort & insertion sort
static void smart_sort(int low, int high)
{
	int i = low;
	for(;;) {
		int diff = high - low;

		// If the length of the chunk to be ordered 
		// is lower than 54 do not use quicksort
		if(diff < 54) {
			if(diff == 1) { 
				// 2 elements -> swap
				if(array[low] > array[high]) {
					uint64_t temp = array[low];
					array[low] = array[high];
					array[high] = temp;
				}
			}
			else {
				// from 3 to 54 elements, use insertion sort
				do {
					if(array[i] > array[i + 1]) {
						uint64_t k = array[i + 1];
						int j = i;
						
						do {
							array[j + 1] = array[j];
						}
						while(--j >= low && array[j] > k);
						
						array[j + 1] = k;
					}
				}
				while(++i < high);

			}
			return;
		}
		// Quicksort
		int j = high;
		
		// Get the pivot element from the middle of the list
		int p = low + (diff >> 1);
		
		uint64_t pivot = array[p];

		// Divide into two lists
		for(;;) {
			// If the current value from the left list is smaller then the pivot
			// element then get the next element from the left list
			while(array[i] < pivot)
				i++;
			
			// If the current value from the right list is larger then the pivot
			// element then get the next element from the right list
			while(array[j] > pivot)
				j--;

			// If we have found a values in the left list which is larger then
			// the pivot element and if we have found a value in the right list
			// which is smaller then the pivot element then we exchange the
			// values.
			// As we are done we can increase i and j
			if(i < j) {
				uint64_t temp = array[i];
				array[i++] = array[j];
				array[j--] = temp;
			}
			else if(i == j) {
				i++;
				j--;
				break;
			}
			else {
				break;
			}
		}
		
		// Recursion
		if (j != low) {
			smart_sort(low, j);
		}
			
		if (i != high) {
			// Tail recursion (old school)!
			//smart_sort(i, high);
			low = i;
		}
		else {
			return;
		}
	}
}

static void array_sort()
{
	smart_sort(0, narray - 1);
}

static void copyright(void)
{
	printf("Colfinder v." VERSION " - Copyright(C) 2026 Matteo Zapparoli\n");
}

static void usage(void) 
{
	copyright();
	printf("Find collisions of first 16 bilions number generated by %s\n\n", prng_name);
	printf("Usage: colfinder [start]\n\n");
}
